### PR TITLE
Add m2k colorimeter experiment board

### PR DESCRIPTION
**Pull request by trupples**
Adding kicad files and gerbers for the revised colorimeter board. Applied all of @mthoren-adi 's [suggestions](https://github.com/trupples/colorimeter-board/issues/1) from the [original repo](https://github.com/trupples/colorimeter-board/). Details in the commit messages.

The new positions for the mechanical holes for mounting the cuvette holder make this revision incompatible with the previous one, but otherwise footprints are 95% in the same place as before.

### CODE REVIEW

**Comment by mthoren-adi** [comment]
Thanks @trupples , I'll review this shortly.

**Comment by mthoren-adi** [comment]
Thanks @amiclaus ! Should all commits be squashed as well?

And @trupples I'm almost done reviewing, I've got an order about ready to go with JLC.

**Review by amiclaus — COMMENTED** [review]
> Thanks @amiclaus ! Should all commits be squashed as well?
> 
> And @trupples I'm almost done reviewing, I've got an order about ready to go with JLC.

If you want to keep history separate for each subfolder, you can keep the rest of the commits. Up to your preference :).

**Comment by trupples** [comment]
Then I guess I'll just squash because there isn't any "history" per se, i just have one commit per component.

**Comment by mthoren-adi** [comment]
Looks good to me, @amiclaus if you're okay with it, can you merge?
Thanks!

**Review by amiclaus — APPROVED** [review]

**Pull request merged**
